### ISSUE TITLE
Java runtime could not be located

### ISSUE THREAD

**Issue by bsaby** [Microsoft/vscode-java-debug#112]
OS: win10
VScode: 1.17.2()x64/x86
Jdk: 1.8.0_151(x64/x86)
Plugin: daily build 59

Repro steps:
1. Install Language Support for Java by Ret hat and Java debug plugin
2. Reload
3. Open a project folder and open a .java file in this project

![image](https://user-images.githubusercontent.com/22470312/31990746-8aca5262-b9a8-11e7-8f9f-f32ccb5beb53.png)
@yaohaizh

**Comment by yaohaizh** [comment]
@bsaby Is the `JAVA_HOME` set in your system environment?

**Comment by bsaby** [comment]
Yes. And after this error occured, restart vscode, Java runtime will work fine.

![image](https://user-images.githubusercontent.com/22470312/31991455-64b7c8e6-b9aa-11e7-8d25-96ce01276afe.png)

**Comment by yaohaizh** [comment]
It seems the value is not properly resolved by VSCode java extension at the first time. You need restart the VSCode after your set the system variable.

**Comment by akaroml** [comment]
@bsaby please verify if you can still reproduce the issue by setting JAVA_HOME properly.

**Comment by bsaby** [comment]
Still reproduce this issue by setting JAVA_HOME properly using daily build 60.
And this issue only reproduce when reload not restart vscode after installing two java plugin

**Comment by akaroml** [comment]
@yaohaizh please further investigate this issue.

**Comment by yaohaizh** [comment]
VSCode will not populate its system environment when reload. See the VSCode issue here: https://github.com/Microsoft/vscode/issues/6333

**Comment by WritingSolutions2020** [comment]
For what it's worth, as of 05 March, 2018 the problem illustrated in the original poster's screenshot still exists.

For Linux Mint 32-bit. Visual Studio code 1.20.1.

1. Installed `/java/jdk1.8.0_161` in `/usr` directory. In `/bin` used `java -version` to verify that the Java executable could be run without error.

2. Added path to JDK in both user and workspace settings: 

**User Settings:**
```
{
   "java.home": "/usr/java/jdk1.8.0_161",
}
```
**Workspace Settings:**
```
{
  "java.home": "/usr/java/jdk1.8.0_161",
  "python.pydev.java.home": "/usr/java/jdk1.8.0_161",
  "python.linting.pylintPath": "/usr/local/bin/pylint",
  "python.pythonPath": "/usr/bin/python3.5",
}
```
3. Although I'm creating Python 3.5 code and not Java code, installed the following extensions in response to guidance offered on this and other forums:

    ![visualstudiocode12installedextensions](https://user-images.githubusercontent.com/3333327/37005322-8e209326-2088-11e8-8b85-c2cbe37c48dc.png)

See also https://stackoverflow.com/questions/46751168/visual-studio-code-cant-find-jdk8

4. Although I have resolved other issues (such as the inabiity of Visual Studio Code to find the system's instance of _pylint_, the JDK problem persists. And as others with this problem have noted, the solutions offered aren't working.

**Comment by andxu** [comment]
@WritingSolutions2020 please give more description of "And as others with this problem have noted, the solutions offered aren't working.", can you give us the a description about your problem:
1. are you editing/debugging java code not python code? 
2. does the error pops show "Java runtime cannot be located"
3. what the env variables of `JAVA_HOME` and `PATH`
4. what's the result of bash/command prompt result of "which java" and "where java", eg:
  <pre>
</pre>

**Comment by WritingSolutions2020** [comment]
Actually I think this may be a PyDev extension problem. The popup shown in the original post doesn't occur  until I open a PY file. (I'm working entirely with Python, not Java).

ANYHOW I've uninstalled Visual Studio Code and moved on.  We can re-close this if you'd like...

**Comment by andxu** [comment]
Thanks for the feed back, close this issue.

**Comment by WritingSolutions2020** [comment]
VSC's documentation and forum comments talk about configuring the editor's USER or WORKSPACE JSON to point to a particular Java SDK. Others then say that the answer" s JAVA_HOME and PATH. **None** are needed. Well, I've gone through all the JSON and JAVA_HOME and PATH stuff. It appears to me that Visual Studio Code is flaky when it comes to working with Java.
 
So in my experience one of Visual Studio Code's central failures is the inability is the clearly defined, unambiguosly accurate, way to  point the editor to whatever JRE or Java SDK is required by the editor and ALL extensions. And to then  receive confirmation from VSC and the extensions that they all have what they need.

I've wasted all day trying to work through this and haven't succeeded. I'm done...

**Comment by bedge** [comment]
Seeing the same as @WritingSolutions2020 with:
VS Code version: Version 1.29.0-insider (1.29.0-insider)
OS and version: OSX High Sierra 10.13.6 (17G65)

Also, I'm using jenv which adds another layer of obfuscation, but all shells show:
```
❯ jenv version
10.0 (set by /Users/bedge/.jenv/version)

❯ java -version
java version "10.0.1" 2018-04-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.1+10)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.1+10, mixed mode)

❯ which java
/Users/bedge/.jenv/shims/java


```

**Comment by joygre1** [comment]
Hello, 
I just started installed the Visual studio Code  and for the life of me, I keep getting the Java run time could not be located and even after using the paths provided, the error remains. Can anyone kindly help this code newbie.

**Comment by testforstephen** [comment]
@joygre1 The checking approach is provided by [Language Support for Java(TM) by Red Hat](https://github.com/redhat-developer/vscode-java) extension, what version did you install Java language support extension?

**Comment by joygre1** [comment]
I found an alternative and deleted the Force.com. No worries  and thanks so much for responding! 

Thanks and regards,

J. Greer

**Comment by RobbiNespu** [comment]
sorry for bump the issue. seem this issue is appear on google 1st page, i share my quick solution. read my explanation below

![javahome](https://user-images.githubusercontent.com/3077875/91248376-1230a300-e787-11ea-87c2-861d762855cf.PNG)
As quick solution, just edit your vscode setting.json and pointing directly to java_home (eg: add ` "java.home": "C:\\java\\jdk\\java-11-openjdk-11.0.8-2",` ). Please refer attached picture, saved it and vscode will ask to restart. After restart, should be no more same issue. I hope this will help.
