### ISSUE TITLE
Flink official demo debug will get error :Cannot find a class with the main method

### ISSUE THREAD

**Issue by rockxsj** [microsoft/vscode-java-debug#478]
[provide a description of the issue]

##### Environment
- Operating System:macos 10.14.1
- JDK version: 1.8.0_144
- Visual Studio Code version:1.29.1
- Java extension version:0.4.0
- Java Debugger extension version:0.15.0

##### Steps To Reproduce
1. curl https://flink.apache.org/q/quickstart.sh | bash -s 1.6.1
2. open the quickstart dir with vscode and press F5 to debug,will get the error:
![image](https://user-images.githubusercontent.com/3021207/48777075-8ade1200-ed0c-11e8-9615-540c000663a3.png)
3. if I assign the class in launch.json, I will get another error:
![image](https://user-images.githubusercontent.com/3021207/48777119-b52fcf80-ed0c-11e8-8f5e-94966498b9e4.png)

[attach a sample project reproducing the error]
[attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

##### Current Result
Cannot find a class with the main method
##### Expected Result
Could debug well.

**Comment by andxu** [comment]
Seems a bug in eclipse maven importer, to solve your problem temporarily, try to 
1. close vscode and eclipse
2. delete .project file and .classpath file(if the root folder has)
3. run `mvn eclipse:eclipse` at the root folder
4. open the root folder in vscode, F5 and you will be able to debug
```
N:\quickstart>mvn eclipse:eclipse
[INFO] Scanning for projects...
[WARNING] The POM for org.eclipse.m2e:lifecycle-mapping:jar:1.0.0 is missing, no dependency information available
[WARNING] Failed to retrieve plugin descriptor for org.eclipse.m2e:lifecycle-mapping:1.0.0: Plugin org.eclipse.m2e:lifecycle-mapping:1.0.0 or one of its dependencies could not be resolved: Failure to find org.eclipse.m2e:lifecycle-mapping:jar:1.0.0 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced
[INFO]
[INFO] ------------------< org.myorg.quickstart:quickstart >-------------------
[INFO] Building Flink Quickstart Job 0.1
[INFO] --------------------------------[ jar ]---------------------------------
[WARNING] The POM for org.eclipse.m2e:lifecycle-mapping:jar:1.0.0 is missing, no dependency information available
[WARNING] Failed to retrieve plugin descriptor for org.eclipse.m2e:lifecycle-mapping:1.0.0: Plugin org.eclipse.m2e:lifecycle-mapping:1.0.0 or one of its dependencies could not be resolved: Failure to find org.eclipse.m2e:lifecycle-mapping:jar:1.0.0 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced
[INFO]
[INFO] >>> maven-eclipse-plugin:2.10:eclipse (default-cli) > generate-resources @ quickstart >>>
[INFO]
[INFO] <<< maven-eclipse-plugin:2.10:eclipse (default-cli) < generate-resources @ quickstart <<<
[INFO]
[INFO]
[INFO] --- maven-eclipse-plugin:2.10:eclipse (default-cli) @ quickstart ---
[INFO] Using Eclipse Workspace: null
[INFO] Adding default classpath container: org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-1.8
[INFO] Wrote settings to N:\quickstart\.settings\org.eclipse.jdt.core.prefs
[INFO] Wrote Eclipse project for "quickstart" to N:\quickstart.
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.552 s
[INFO] Finished at: 2018-11-21T15:57:50+08:00
[INFO] ------------------------------------------------------------------------
```

**Comment by rockxsj** [comment]
tks! this workaround work well! 👍

**Comment by Zeus-Iqd** [comment]
mac how to do

**Comment by Zeus-Iqd** [comment]
您好，请问下mac下要怎么做？@andxu

**Comment by Zeus-Iqd** [comment]
@andxu 请问下mac要怎么做？

**Comment by andxu** [comment]
@Zeus-Iqd 是同样的项目吗？如果是的话，在pom.xml里删掉lifecycle-mapping插件，如果不是的话，可不可以attach一个你的project？

**Comment by rockxsj** [comment]
> @andxu 请问下mac要怎么做？

一样的，就按照@andxu 说的做就行了

**Comment by StanWang798** [comment]
@andxu 
I'm stuck by this tiny problem for almost 3 days.  Hope to see this plugin conflict fixed in the future or notified in some any to avoid vscode malfunctioning. 🥺

**Comment by surgura** [comment]
This bug still remains. As andxu said, removing the eclipse plugins stuff from the pom solves the problem. Big thanks, I was about to give up.

**Comment by tomercagan** [comment]
I have had the same issue (end of 2020) - failed to run/debug and no linting / code completion etc.

Manually removed the Eclipse dependency from `pom.xml`, lines 168-211 (the eclipse plugin is lines 172-209 but removing it leave an empty `pluginManagement/plugins` hierarchy) immediately asked to refresh the project and following that both coding support and execution worked.

Given that they documentation do not recommend using Eclipse - maybe that plugin should be removed from the template...

**Comment by Jasonzhaochen** [comment]
I was about to give up and switch to IntelliJ IDEA. Thank you all!

**Comment by xingzhuimeteorite** [comment]
I was about to give up and switch to IntelliJ IDEA. Thank you all!

**Comment by afreemanio** [comment]
Can confirm still a problem - was about to switch to IDEA or eclipse, thank you for the answer

**Comment by tasty0tomato** [comment]
I have a question. Why does lifecycle-mapping influence?

**Comment by davidradl** [comment]
@tasty0tomato I am trying to get Flink to work with Visual Studio code, why do you think this is an issue with an out of data flink demo. I cannot get this working with the current Flink demo; are you saying that it is now fixed with the latest Flink?

**Comment by tasty0tomato** [comment]
@davidradl Please delete the  `lifecycle-mapping` plugin in pom.xml which is used to develop in Eclipse, but seems to not work with VSCode.

**Comment by davidradl** [comment]
@tasty0tomato thanks for you quick response - I will give it a go
