### ISSUE TITLE
Lambda evaluation - Cannot evaluate because of compilation error(s): Evaluations must contain either an expression or a block of well-formed statements

### ISSUE THREAD

**Issue by spottedmahn** [microsoft/vscode-java-debug#754]
##### Environment
- Operating System: Win 10
- JDK version: openjdk version "11.0.5" 2019-10-15
- Java extension version: ?? do you mean "Language Support for Java(TM) by Red Hat"? if so 0.55.1
- Java Debugger extension version: 0.24.0
- Visual Studio Code Version: 1.41.1 (user setup)
- Commit: 26076a4de974ead31f97692a0d32f90d735645c0
- Date: 2019-12-18T14:58:56.166Z
- Electron: 6.1.5
- Chrome: 76.0.3809.146
- Node.js: 12.4.0
- V8: 7.6.303.31-electron.0
- OS: Windows_NT x64 10.0.18363

##### Steps To Reproduce
1. Use a `Stream.forEach()` and try to evaluate something in the debug console

[Sample project](https://github.com/spottedmahn/experiments-2020/blob/cannot-evaluate-in-lamda/java-tests-issue/src/test/java/miked/javatestsissue/LibraryTest.java)

[java test runner - can't evaluate.log](https://github.com/microsoft/vscode-java-debug/files/4123098/java.test.runner.-.can.t.evaluate.log)

##### Current Result

![image](https://user-images.githubusercontent.com/14079228/73277058-a027b980-41b7-11ea-8d12-d25c747b635b.png)

maybe it more has to do w/ lambda's? 🤔

![image](https://user-images.githubusercontent.com/14079228/73277123-b170c600-41b7-11ea-8695-bef9bf28b5e3.png)

##### Expected Result

![image](https://user-images.githubusercontent.com/14079228/73277140-b6ce1080-41b7-11ea-8c5e-bf0543adcff2.png)

![image](https://user-images.githubusercontent.com/14079228/73277153-b9c90100-41b7-11ea-87d2-481a37ace339.png)

**Comment by spottedmahn** [comment]
Also, the debugger variables window is able to see the values:

![image](https://user-images.githubusercontent.com/14079228/73691410-4c7a0c00-46a0-11ea-923d-00820380700d.png)

**Comment by akaroml** [comment]
@spottedmahn thanks for reaching out. It looks like a bug to me. @testforstephen please take a look.

**Comment by testforstephen** [comment]
The upstream jdt has the same error on inspecting variable in the lambda expression. Need take a look at the upstream jdt first.

**Comment by spottedmahn** [comment]
upstream jdt is https://github.com/eclipse/eclipse.jdt.debug? 🤔

**Comment by puremourning** [comment]
Apologies for slightly hijacking this issue, but i have a very similar issue and want to check if it is same/related. When trying to evaluate in generic code, all evaluations fail with "Cannot evaluate because of a compilation error(s): Evaluations must contain either an expression or a block of well-formed statements". This is not a lambda, it's just a plain method of a (generic) type. I tried a trivial example and expressions worked with generics, so does this sound like the same bug ?

**Comment by noel-yap** [comment]
Any update on this issue? This is adding a lot of friction for me while debugging.

**Comment by testforstephen** [comment]
The upstream has added the support for the lambda support in 2020-03 release, and already integrated to the debugger extension.

@puremourning @noel-yap Could you please open a new bug for your issue? Also please add the code snippet to explain your scenario.

**Comment by rposener** [comment]
@akaroml @testforstephen - any idea when that eclipse fix will be incorporated with vs code extension / tools?  Also, looking at the issue on the eclipse site it appears that working with streams it's still not fixed.

**Comment by testforstephen** [comment]
Debugger 0.27.0 just released today, the fix should be already there. Could you try again?

**Comment by basecell** [comment]
![image](https://user-images.githubusercontent.com/14192199/97825574-08349e80-1cfa-11eb-8ce1-c2ac4cb7501b.png)
Obviously, this problem is still unresolved, sad.

**Comment by massimeddu-sonic** [comment]
Hi all,

I've the same issue trying to evaluating expression in a Tomcat application. Do you know how to solve it?

Thanks,

**Comment by michaellilltokiwa** [comment]
@akaroml since this is not fixed, please consider reopening.

**Comment by testforstephen** [comment]
let's reopen the issue and revisit it.

**Comment by testforstephen** [comment]
The evaluation of partial lambda expressions has been supported in the latest version of the debugger, and we will keep investigating the root cause of the unsupported cases.

- **Supported cases**
  - Lambdas from JDK standard libs (e.g. Java Steams) are supported.
![image](https://user-images.githubusercontent.com/14052197/145927740-b03821a2-755b-4b9c-a88d-6daea167a244.png)

- **Unsupported cases**
   - external variables from enclosing method are not supported.
     ![image](https://user-images.githubusercontent.com/14052197/145927646-2f90b5c1-be95-4f47-a7b8-d8a9974983f6.png)

   - Lambdas from third-party libraries are not supported.
![image](https://user-images.githubusercontent.com/14052197/145928087-ed0a7b10-2e0f-47e6-bc0f-1d404cc24079.png)

**Comment by testforstephen** [comment]
Opened issues on the upstream JDT to track the progress.
- [Bug 578145](https://bugs.eclipse.org/bugs/show_bug.cgi?id=578145) - Evaluations are not working on chain calls for lambda variables.
- [Bug 578147](https://bugs.eclipse.org/bugs/show_bug.cgi?id=578147) - Evaluations for lambda variables are not working when using generic type arguments on lambda.

**Comment by testforstephen** [comment]
Hi all, we have fixed the lambda evaluation bug in the upstream eclipse jdt repository.

Please update **Language Support for Java(TM) by Red Hat** to latest version **1.5.0**, which includes our fix for lambda evaluation.

// fyi: @spottedmahn @noel-yap @rposener @puremourning @refcell @michaellilltokiwa @massimeddu-sonic @prumseycsi @acodervic @praxem @ahmednrana

**Comment by prumseycsi** [comment]
Apparently not a duplicate of my problem reported to #844.  Redhat 1.5 does not fix it.  Please reopen something, or tell me to open something new.

**Comment by testforstephen** [comment]
@prumseycsi The original issue reported at #844 is about the compilation errors for lambda variable evaluation. Have a look at your comment https://github.com/microsoft/vscode-java-debug/issues/844#issuecomment-822184817, I don't understand what's your use case, could you pls open a new issue to describe your problem?

**Comment by martinkunc** [comment]
Hi, I have a similar problem with internal field initializer.
```
import java.util.*;
public class RomanToInteger {
    public int romanToInt(String s) {
        var ri = new HashMap<Character,Integer>() {{ 
            put('I', 1);
        }};
        var c = ri.get(s.charAt(0)); // ri returns cannot evaluate
        return 0;
    }
}
```
![cannot-evaluate](https://user-images.githubusercontent.com/5441732/168485286-d5ebf9ac-2169-427d-9037-47adb1540601.png)

Environment
Operating System: Win 11
JDK version: openjdk version "11.0.12" 2021-07-20
Java extension version: Language Support for Java(TM) by Red Hat 0.40.1
Java Debugger extension version: 0.40.1
Visual Studio Code Version: 1.67.1
Commit: da15b6fd3ef856477bf6f4fb29ba1b7af717770d

**Comment by testforstephen** [comment]
@martinkunc Your case is not related with this issue, I created a new one to track your case. https://github.com/microsoft/vscode-java-debug/issues/1163
